name: issue and PR lifecycle

on:
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, labeled]
  schedule:
    - cron: '0 9 * * *'

permissions:
  issues: write
  pull-requests: write
  contents: write  # on-pr-lgtm job requires write to enable auto-merge

jobs:
  lifecycle:
    uses: projectbluefin/actions/.github/workflows/lifecycle.yml@main
    with:
      brand_name: "Common"
    secrets: inherit
