name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"
      - "**.just"
  push:
    branches:
      - main
    paths:
      - "Justfile"
      - "**.just"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: Check Just Syntax
        shell: bash
        run: |
          just check
